### ISSUE TITLE
Thank You

### ISSUE THREAD

**Issue by ronaldpetty** [krlawrence/graph#1]
Not a new issue, but you solved an existing one.  Thanks for the hard work on this.

**Comment by krlawrence** [comment]
You are very kind @ronaldpetty - Thank you. It means a lot.

**Comment by jbmusso** [comment]
Jumping in. Wow, amazing piece of work @krlawrence! Thank you for sharing this.

**Comment by krlawrence** [comment]
Thanks @jbmusso

**Comment by emehrkay** [comment]
Yes. Thank you very much for this. It is missing from the Tinkerpop community

**Comment by krlawrence** [comment]
Thanks @emehrkay
