### ISSUE TITLE
Issue with querying properties of a vertex

### ISSUE THREAD

**Issue by nitin9nair** [krlawrence/graph#10]
I am using **Gremlin version 3.3.0** and not able to query the properties of any vertex.

Example:
`g.V(3).valueMap(true).unfold()`

The above query doesnot return any result of the **properties of vertex 3**

Please look into the issue in your book in **2.4. Introducing the air-routes graph** and rectify the issue.

**Comment by nitin9nair** [comment]
I got the answer related to above query that is to add **inverted commas ( ' ' )** so it will interpret as a string.
May be the same issue will not be there with the earlier versions of Gremlin console.

@krlawrence What is your opinion about this particular issue ?

**Comment by krlawrence** [comment]
That query works for me on Gremlin 3.3 - are you getting an error message?
```
gremlin> Gremlin.version
log4j:WARN No appenders could be found for logger (com.jcabi.manifests.Manifests).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
==>3.3.0
gremlin> g.V(3).valueMap(true).unfold()
==>country=[US]
==>code=[AUS]
==>longest=[12250]
==>city=[Austin]
==>lon=[-97.6698989868164]
==>type=[airport]
==>elev=[542]
==>icao=[KAUS]
==>region=[US-TX]
==>runways=[2]
==>lat=[30.1944999694824]
==>id=3
==>label=airport
==>desc=[Austin Bergstrom International Airport]
gremlin>
```
@nitin9nair

**Comment by krlawrence** [comment]
Did you load the graph into TinkerGraph using the steps in the book or maybe into another graph like Janus? @nitin9nair

**Comment by nitin9nair** [comment]
@krlawrence 

To get the Gremlin version :
```
gremlin> Gremlin.version
log4j:WARN No appenders could be found for logger (com.jcabi.manifests.Manifests).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
==>3.3.0
```

I have renamed the file from **air-routes.graphml** to **air.graphml**
then loaded the graph into TinkerGraph using following steps:
```
gremlin> graph = TinkerGraph.open()
==>tinkergraph[vertices:0 edges:0]
gremlin> graph.io(graphml()).readGraph('D:/air.graphml')
==>null
gremlin> graph.toString()
==>tinkergraph[vertices:3619 edges:50148]
gremlin> g = graph.traversal()
==>graphtraversalsource[tinkergraph[vertices:3619 edges:50148], standard]
```

Then I ran the below query to get properties of vertex but it does not provide any result.
```
gremlin> g.V(3).valueMap(true).unfold()
gremlin>
```

But with inverted commas its working-
```
gremlin> g.V('3').valueMap(true).unfold()
==>country=[US]
==>code=[AUS]
==>longest=[12250]
==>city=[Austin]
==>label=airport
==>lon=[-97.6698989868164]
==>type=[airport]
==>id=3
==>elev=[542]
==>icao=[KAUS]
==>region=[US-TX]
==>runways=[2]
==>lat=[30.1944999694824]
==>desc=[Austin Bergstrom International Airport]
```

**Comment by krlawrence** [comment]
Did you use the setup steps I show in the book that create an ID manager? @nitin9nair  If not that would explain what you are seeing. My steps tell TinkerGraph that the IDs are LONG calues.

**Comment by krlawrence** [comment]
I will add a note in the next update to reinforce that these steps are important.

**Comment by krlawrence** [comment]
I added a note to the section on loading the air-routes graph to emphasize that setting up the ID managers is important. That will be part of the revision 271 update. It's already in the adoc file.
