### ISSUE TITLE
In-Out degree examples are back to front - Section 3.26

### ISSUE THREAD

**Issue by steffan-westcott** [krlawrence/graph#100]
The examples in section 3.26 seem to have confused in-degree with out-degree. Take the first example:
```groovy
// Out degree (number of routes) from each vertex (airport)
g.V().hasLabel('airport').out('route').groupCount().by('code')
```
This is actually calculating the in-degree of each airport vertex, not the out-degree. The out-degree of AMS is 269, not 272. The airport with highest out-degree is FRA, not AMS. The other examples in the section also seem to have this issue.

**Comment by krlawrence** [comment]
Thanks Stefan. I’ll clean this section up. A while back I updated the examples to line up with the same graph version. Looks like I missed a few. I’ll also clean up Amy degree issues.

**Comment by steffan-westcott** [comment]
The first two examples in section 5.1.11 also have the same issue, they are actually calculating the count of routes to the airports, not from the airports:
```groovy
// How many flights are there from each airport?
g.V().hasLabel('airport').out().groupCount().by('code')

// count the routes from all the airports and then select a few.
g.V().hasLabel('airport').out().groupCount().by('code').
      select('AUS','AMS','JFK','DUB','MEX')
```

**Comment by krlawrence** [comment]
Fixed in Release 280
