### ISSUE TITLE
Minor typo: fold step returns a list - Section 4.9.1

### ISSUE THREAD

**Issue by steffan-westcott** [krlawrence/graph#102]
3rd paragraph should read as follows (corrections in bold):
> Likewise, when we use the fold step a **list** is generated. We can use the order step with a local scope to order the contents of the **list**.

**Comment by krlawrence** [comment]
Thanks. I made the fix.

**Comment by steffan-westcott** [comment]
Thanks for the fix, but I think you missed another mention of `map` earlier in the sentence :)

**Comment by krlawrence** [comment]
Doh! I'll fix it.

**Comment by krlawrence** [comment]
Fixed in Release 280
