### ISSUE TITLE
local is unnecessary - Section 5.7

### ISSUE THREAD

**Issue by steffan-westcott** [krlawrence/graph#105]
The text suggests `local` is needed for the random walk, but this query without it (and a spurious `by` step) appears to work also:
```groovy
// Random walk with five hops
g.V().has('code','AUS').repeat(bothE('route').
      sample(1).otherV()).times(5).
      path().by('code').by('dist')
```
I don't understand what bearing `local` has on this query. If `local` is removed from the example, some of the explanation before this example also needs attention.

**Comment by krlawrence** [comment]
I have been thinking about this quite a bit more. I think some additional examples where local is not used, with explanations would be a good addition.

**Comment by krlawrence** [comment]
The TinkerPop official documentation is getting an update. I will update the book to reflect these clarifications.

https://github.com/apache/tinkerpop/commit/aef2f6ca0f8f1f62cb8220b01afc49d70714692f

**Comment by krlawrence** [comment]
Fixed in Release 280
