### ISSUE TITLE
Discuss terminal steps

### ISSUE THREAD

**Issue by pluradj** [krlawrence/graph#111]
One the most common stumbling blocks that developers run into when building an application with Gremlin is that the reference docs tend to assume that the traversals are being run in the Gremlin Console, which auto-iterates the traversal.

When they move to write a program outside of the console, they need to be aware that they need to _iterate the traversal_. I had previously added a section to this to the JanusGraph docs. 

* https://tinkerpop.apache.org/docs/current/reference/#terminal-steps
* https://docs.janusgraph.org/latest/gremlin.html#_iterating_the_traversal

In the book, there is some mention of terminating steps in Chapter 3.6 http://kelvinlawrence.net/book/Gremlin-Graph-Guide.html#var

**Comment by krlawrence** [comment]
Thanks @pluradj. I will think about how to call them out more obviously. I agree this is a common stumbling block.

**Comment by pluradj** [comment]
I ran across this again today when using the `:record` feature. If you don't use the terminating step `next()` in your example in [2.2.2 Saving output from the console to a file](http://kelvinlawrence.net/book/Gremlin-Graph-Guide.html#gremlinsave), the result in the text file contains the `toString()` version of the traversal rather than the execution result.

I think it's worth mentioning terminal steps earlier rather than later. The Gremlin Console has the auto-iteration behavior which makes them unnecessary for single statement queries. If you string together multiple statements in a single line, you would still need to use the terminal steps.

```
gremlin> x = g.V().count(); "there are " + x + " vertices"
==>there are [GraphStep(vertex,[]), CountGlobalStep] vertices
gremlin> x = g.V().count().next(); "there are " + x + " vertices"
==>there are 6 vertices
```
