### ISSUE TITLE
Explanation of "__" better moved to section 3.14

### ISSUE THREAD

**Issue by dfirka** [krlawrence/graph#112]
I am new to Java/Groovy, so i couldn understand the symbol 

> __

 in query 

```
g.V().has('airport','code','AUS').       
out().not(where(__.in('contains').has('code','US'))).       
valueMap('code','city')
```

Which is explained later in page 132:

> Notice that I added the "__." (underscore underscore period) in front of the in(). This is shorthand for "the thing we are currently looking at", so in this case, the result of the has step.

it will be better to move that paragraph to the first usage of __

thxs
dan

**Comment by krlawrence** [comment]
Thanks for taking the time to provide the feedback Dan (@dfirka ). I will definitely do something to make that improvement.

**Comment by krlawrence** [comment]
Fixed in Release 280
