### ISSUE TITLE
Minor typos

### ISSUE THREAD

**Issue by jerryjch** [krlawrence/graph#113]
In the sample-data/README.md:

There is also a small Groovy script in the '/sample-code' folder called 'graph-stats.groovy' that can be run from within the Gremlin console to produce some statistics about the graph **similr** to those found in the **boook** and in the 'README-air-routes.txt file'.

Typo in **bold**.

**Comment by krlawrence** [comment]
Thanks for finding this and taking time to open an issue.

**Comment by krlawrence** [comment]
Fixed in Release 280
