### ISSUE TITLE
Fix syntax for adding vertices and edges

### ISSUE THREAD

**Issue by divijvaidya** [krlawrence/graph#12]
In section **4.5 Adding vertices, edges and properties**, you recommend a way of adding edges which are not valid syntax for Gremlin queries.

**Query being referred here:**
`g.V().has('code','DFW').addE('route').to(V().has('code','XYZ'))`

**Steps to reproduce:**

1. Download the latest Tinkerpop server (currently 3.3.0)

2. Start the server in secure mode which enables the groovy static compilation type check (I removed the ssl authentication for the sake of this demo)
`./bin/gremlin-server.sh conf/gremlin-server-secure.yaml`

3. Run the following commands on the console
 
```
gremlin> :remote connect tinkerpop.server conf/remote.yaml
==>Configured localhost/127.0.0.1:8182
gremlin> :remote console
==>All scripts will now be sent to Gremlin Server - [localhost/127.0.0.1:8182] - type ':remote console' to return to local mode
gremlin> g
==>graphtraversalsource[tinkergraph[vertices:0 edges:0], standard]
gremlin> g.addV('airport').property('code','XYZ')
==>v[0]
gremlin> g.addV('airport').property('code','DFW')
==>v[2]
gremlin> g.V().has('code','DFW').addE('route').to(V().has('code','XYZ'))
Script6.groovy: 1: [Static type checking] - Cannot call org.apache.tinkerpop.gremlin.process.traversal.dsl.graph.GraphTraversal <org.apache.tinkerpop.gremlin.structure.Vertex, org.apache.tinkerpop.gremlin.structure.Edge>#to(org.apache.tinkerpop.gremlin.process.traversal.Traversal <org.apache.tinkerpop.gremlin.structure.Edge, org.apache.tinkerpop.gremlin.structure.Vertex>) with arguments [org.apache.tinkerpop.gremlin.process.traversal.dsl.graph.GraphTraversal <A extends java.lang.Object, org.apache.tinkerpop.gremlin.structure.Vertex>]
 @ line 1, column 1.
   g.V().has('code','DFW').addE('route').to(V().has('code','XYZ'))
   ^

1 error
Type ':help' or ':h' for help.
Display stack trace? [yN]
gremlin> g.V().has('code','DFW').as('a').V().has('code','XYZ').as('b').addE('route').from('a').to('b')
==>e[4][2-route->0]
```

As you can see, the query you suggest in the tutorial fails with an error. I have also included an example of a query which achieves the same result.

**Why does the syntax work without groovy static compilation?**
From what I understand here, the `to(V().has('code','XYZ'))` part in the query uses anonymous traversal which methods which are parameterized over type in its [java implementation](https://github.com/apache/tinkerpop/blob/master/gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/dsl/graph/__.java) in Tinkerpop's implementation. Without static compilation, groovy creates JVM objects at runtime which do not have typed arguments to its type parameters, hence, the runtime succeeds with every parameter type being Object. Once we enable static compile time type inference, it assigns arguments to the type parameters and thus, fails because the syntax is invalid in Java.

**Comment by krlawrence** [comment]
Thanks for the feedback. Keep in mind all these examples are designed to be run using the Gremlin Console locally with a local TinkerGraph. There are a lot of things to be done differently when talking to a remote Gremlin Server. I have a separate section for that that I still need to fill in.

```
gremlin> xyz = g.addV('airport').property('code','XYZ').
......1>                         property('icao','KXYZ').
......2>                         property('desc','This is not a real airport').next()
==>v[54415]
gremlin> g.V().has('code','DFW').addE('route').to(V().has('code','XYZ'))
==>e[54419][8-route->54415]
gremlin>
```

I will add a note that this may not work with Gremlin Server and also when the Gremlin Server section gets written add some alternative examples.

**Comment by krlawrence** [comment]
I just uploaded a draft of what will be the 273 version with changes to this section to remove some of the usage of V() as it is no longer necessary in TP 3.3 and also added a specific comment about Gremlin Server.

Thanks again for your great feedback @divijvaidya

**Comment by divijvaidya** [comment]
Thank you for taking the time out to write this awesome guide.
