### ISSUE TITLE
Query samples page 18 did not work because of store type ID

### ISSUE THREAD

**Issue by ErikvdVen** [krlawrence/graph#126]
One thing worth being noted, is my issue on StackOverflow, [click here](https://stackoverflow.com/questions/52389980/cannot-access-specific-vertex-by-id-using-tinkergraph-in-gremlin-console/52390113#52390113). The issue was that I was stuck at page 18 of the PDF version of the book.

I loaded the `air-routes-latest.graphml` in Tinkergraph using the noted query commands but `g.V(3).valueMap(true).unfold()` did not give me any results in return. `g.V()` however, did. It seems that the id's of the vertices were stored as `string` instead of `integer`. So after updating the query to `g.V("3").valueMap(true).unfold()` (note the quotation marks ""), I did get a respond from the TinkerGraph.

So guess it might be a good idea to add some information (or a link) about how to make sure the ID's will be stored as `integer`, as mentioned in chapter 2.6, before providing sample queries already, or update the queries with some note that the query might differ depending on how the ID's are stored, as integer or as string.

**Comment by krlawrence** [comment]
Hi @ErikvdVen - Thanks for taking the time to open this issue. I probably did not anticipate anyone would try the examples before I explained how to load the graph! I will put some sort of tip or note into the section that confused you. Thanks again for making time to open this issue.

**Comment by krlawrence** [comment]
Fixed in release 281. Published Dec 26th 2018
