### ISSUE TITLE
Use GitHub releases for book version build outputs

### ISSUE THREAD

**Issue by mbrukman** [krlawrence/graph#13]
Right now, new builds of the book are being submitted via Git to https://github.com/krlawrence/graph/tree/master/book which is growing the total size of the Git repo (since Git history stores all past versions), even though typically users will only want the latest version, while developers need to keep syncing the full Git history to contribute to this repo.

What about using the [GitHub "Releases" feature](https://help.github.com/articles/creating-releases/) (which seems to be disabled in this repo) to store each new build instead of keeping it in version control?

**Comment by krlawrence** [comment]
That's a really good suggestion @mbrukman . Thanks! Over the break I will try and get that setup..

**Comment by mbrukman** [comment]
Note that due to the historical inclusion of binary files in this repo, it is now ~50MB for a clean checkout:

```bash
$ git clone https://github.com/krlawrence/graph
$ du -shc graph
 49M	graph
 49M	total
```

One way to address this, given that there are only a few stars + forks is by starting with a brand new repo (e.g., call it `graph-book`) and start from a clean slate, with no binary files, and leave this repo as-is (since there are links pointing to it), but mark it deprecated and redirect folks to the new repo.

The other alternatives are:

* modify this repo in-place which is destructive modification as it rewrites git history and breaks all forks
* leave it as-is

Thoughts?

**Comment by krlawrence** [comment]
Given a lot of people now know about this URL, I think the modify in place might be the way to go for a one time clean up.

**Comment by krlawrence** [comment]
I just created a v274 release and removed the "binaries" from the /book folder.

**Comment by krlawrence** [comment]
As a side note, I removed the files from the Git commit history also but I am not sure if Git will fully let go of the files as other people have references to them in forks. I have not seen the disk usage go down more than about 2mb. At least moving forward it should not grow very fast.

**Comment by krlawrence** [comment]
I ended up using `git clone --mirror` and running `BFG`. That worked a lot better than `git filter-branch`. The repo is down to 20M now and the .git folder is down to 5.7mb from about 34mb.

This will have broken forks sadly but worst case people have to re-clone etc and this is a much better state to be in moving forward.

**Comment by krlawrence** [comment]
I am going to close the issue as I believe it is now resolved. Please reopen it if you see anything that I missed.
