### ISSUE TITLE
wrong output in pdf

### ISSUE THREAD

**Issue by hgrill** [krlawrence/graph#130]
Version 281-preview, November 4th 2018
On page 33 of the pdf-version the command 
g.V().hasLabel('airport').groupCount().by('country').select('FR') 
shows 
59

That is wrong, should be 58.

**Comment by krlawrence** [comment]
Thanks for taking the time to report this. I’ll get it fixed as needed

**Comment by krlawrence** [comment]
I see what I did! In the latest data file `air-routes-latest.graphml` there are 59 airports in France but in the original `air-routes.graphml` that the book is supposed to follow there are only 58. I will make the change Thanks for finding this and taking the time to open an issue.

**Comment by hgrill** [comment]
Thanks for this good book about Gremlin and Janusgraph. It helps me a lot . 

________________________________
Von: Kelvin Lawrence <notifications@github.com>
Gesendet: Samstag, 17. November 2018 15:41
An: krlawrence/graph
Cc: Heiko Grill; Author
Betreff: Re: [krlawrence/graph] wrong output in pdf (#130) 

I see what I did! In the latest data file air-routes-latest.graphml there are 59 airports in France but in the original air-routes.graphml that the book is supposed to follow there are only 58. I will make the change Thanks for finding this and taking the time to open an issue.

**Comment by krlawrence** [comment]
Fixed in release 281. Published Dec 26th 2018
