### ISSUE TITLE
Errata - 

### ISSUE THREAD

**Issue by ghu81933** [krlawrence/graph#135]
**_Section 3.2.4. Counting groups of things_**
**Current Text:**
The group and groupCount steps are very useful when you want to count groups of things or collect things into group using a selection criteria.

**New Text (added 'a' between into and group):**
The group and groupCount steps are very useful when you want to count groups of things or collect things into **a** group using a selection criteria.

**_Section 3.3.2. What vertices and edges did I visit? - Introducing path_**
**Current Text:**
If if there are not enough modulators specified for the total number of elements in the path, Gremlin just loops back around to the first by step and so on.

**New Text (remove double if):**
If there are not enough modulators specified for the total number of elements in the path, Gremlin just loops back around to the first by step and so on.

**_3.6.1. Introducing toList, toSet, bulkSet and fill_**
**Current Text:**
The asBulk method returns a map of key/value pairs where the key is the number and the value is the number of time that number appears in the set.

**New Text (changed time to times):**
The asBulk method returns a map of key/value pairs where the key is the number and the value is the number of time**s** that number appears in the set.

**Comment by krlawrence** [comment]
Thanks for taking the time to report these. I have some other wording changes I also need to do. I will factor these into that edit.

**Comment by krlawrence** [comment]
Fixed in release 282 - October 25th 2019
