### ISSUE TITLE
Syntax Error: Accessing particular vertex is done like g.V(3) but instead it should be g.V('3')

### ISSUE THREAD

**Issue by nitin065** [krlawrence/graph#141]
Gremlin version: 3.4.0
g.V(3) returns no result.
g.V('3') returns v[3].

**Comment by krlawrence** [comment]
You need to setup the ID managers as shown early in the book. Did you try that?

**Comment by krlawrence** [comment]
```
gremlin> Gremlin.version
==>3.4.0
gremlin> g.V(3)
==>v[3]
gremlin> g.V(3).values()
==>US
==>AUS
==>12250
==>Austin
==>542
==>KAUS
==>-97.6698989868164
==>airport
==>US-TX
==>2
==>30.1944999694824
==>Austin Bergstrom International Airport
```

**Comment by nitin065** [comment]
> You need to setup the ID managers as shown early in the book. Did you try that?
> 
> ```
> conf = new BaseConfiguration()
> conf.setProperty("gremlin.tinkergraph.vertexIdManager","LONG")
> conf.setProperty("gremlin.tinkergraph.edgeIdManager","LONG")
> conf.setProperty("gremlin.tinkergraph.vertexPropertyIdManager","LONG");[]
> graph = TinkerGraph.open(conf)
> graph.io(graphml()).readGraph('air-routes.graphml')
> g=graph.traversal()
> :set max-iteration 1000
> ```

Oh, sorry. I thought it is specific to groovy not gremlin, so I skipped that part.
Not sure I can close this ticket, if not please do so. Thanks.
