### ISSUE TITLE
Typo in upsert pattern 

### ISSUE THREAD

**Issue by msacks16** [krlawrence/graph#148]
https://kelvinlawrence.net/book/Gremlin-Graph-Guide.html#upsert
g.V(3).fold().
       coalesce(unfold().property('runways','3'),
       addV('airport').property('runways',3))

v[3]

should be:

g.V(3).fold().
       coalesce(unfold().property('runways',3),
       addV('airport').property('runways',3))

v[3]

**Comment by krlawrence** [comment]
Thanks Max

**Comment by krlawrence** [comment]
v
