### ISSUE TITLE
Problem with neptune while running contains query

### ISSUE THREAD

**Issue by vikaskumardixit** [krlawrence/graph#149]
I tried below query for searching in neptune through gremlin

    ` g.V().hasLabel('person').filter{it.get().property('name').value().contains('apt')}`
but it throw and exception that is
 
`org.apache.tinkerpop.gremlin.jsr223.console.RemoteException: {"requestId":"**********","code":"MalformedQueryException","detailedMessage":"Query parsing failed at line 1, character position at 36, error message : token recognition error at: 'et'"`

**Comment by krlawrence** [comment]
Thanks for the feedback. As mentioned in the book using in line lambda code is discouraged and may not be supported by many hosted graph DBs for security and other reasons. You should rewrite the query to use just Gremlin steps and avoid lambdas/closures. 

The new text predicates added in TinkerPop 3.4 will allow you to do these kinds of operations without needing lambdas. Once Neptune has support for those predicates that will be the way to do something like a text contains operation.

**Comment by krlawrence** [comment]
I will review the text UI see if I need to add additional tips about the limitations of relying on closures in queries.

**Comment by vikaskumardixit** [comment]
> Thanks for the feedback. As mentioned in the book using in line lambda code is discouraged and may not be supported by many hosted graph DBs for security and other reasons. You should rewrite the query to use just Gremlin steps and avoid lambdas/closures.
> 
> The new text predicates added in TinkerPop 3.4 will allow you to do these kinds of operations without needing lambdas. Once Neptune has support for those predicates that will be the way to do something like a text contains operation.

Thanks @krlawrence 
I was trying to connect Neptune through Gremlin console 3.4.1, but I'm getting a "Mark host as unavailable"

`org.apache.tinkerpop.gremlin.driver.Host  - Marking Host{address={neptune-address}, ostUri=ws://{neptune-address}:{port}/gremlin} as unavailable. Trying to reconnect.`

Please suggest a workaround or any configuration changes required for this newer version.

**Comment by krlawrence** [comment]
Where are you running the console from? An EC2 instance in the same VPC as Neptune or ... ? Perhaps we should move this discussion to email. Feel free to email me. Also - What does your YAML file look like?

**Comment by vikaskumardixit** [comment]
Yes i am running console on EC2 instance in the save VPC as Neptune. It was working for 3.3.2 but when i try to use 3.4.1 it's not able to connect it try to reconnect again and again.

**Comment by krlawrence** [comment]
As this is not really about the book per-se I answered your question on the Neptune forum at https://forums.aws.amazon.com/thread.jspa?messageID=897967&#897967

**Comment by vikaskumardixit** [comment]
thanks @krlawrence 
Now it's connecting properly but textContains and containing is not working with neptune.

**Comment by 00linglin** [comment]
textContains is a JanusGraph extension, it is not supported by Neptune. containing is new as of Gremlin 3.4.0, Neptune is currently on Gremlin 3.3.2. @vikaskumardixit

**Comment by krlawrence** [comment]
Hello - @vikaskumardixit I am very happy to help you but please do not open Neptune specific issues against the book text and then once I have assigned an issue for investigation as a possible clarifiaction case, please do not edit the title and subject to ask a totally different questions. I will absolutely help you but this is the wrong place to ask those questions. Please ask Neptune questions in the Amazon Neptune specific forum [1] and you will definitely get lots of help. You should expect to see TinkerPop 3.3 features appearing in Neptune soon I believe.

[1] https://forums.aws.amazon.com/forum.jspa?forumID=253&start=0
