### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by isaactzab** [krlawrence/graph#155]
Hello, my name is Levi. 
This book is amazing. I think that would be great if we can translate.
I have forked it and create a "Spanish-translation" branch. I don't know if this is the right way, but I want to collaborate.
[Here is my repo](https://github.com/isaactzab/graph/blob/spanish-translation/book/Gremlin-Graph-Guide.adoc).
If its necessary I can move it to another place. Thank you.

**Comment by krlawrence** [comment]
Thanks for letting me know and thanks for taking this on!

**Comment by krlawrence** [comment]
Should we perhaps create a sub folder here for the Spanish version @isaactzab ? - totally your choice. Really super that you are willing to take this on and help Spanish speakers learn Gremlin!

**Comment by isaactzab** [comment]
a new folder should work!

**Comment by isaactzab** [comment]
Maybe a folder with a subfolders with transaltions. using iso codes for languages.

**Comment by krlawrence** [comment]
Closing for now as the work appears to have not continued. Please feel free to re-open this issue if you do intend to complete the work.
