### ISSUE TITLE
Replace "Janus Graph" with "JanusGraph"

### ISSUE THREAD

**Issue by mbrukman** [krlawrence/graph#16]
The official name of the project (and the trademark that The Linux Foundation holds) is for the single word "JanusGraph", not the two-word phrase "Janus Graph".

The two-word phrase should be globally updated to be a single word.

**Comment by krlawrence** [comment]
Fixed - thanks for the reminder!

**Comment by mbrukman** [comment]
Did you make the headings makers the same length after doing a global search-and-replace to remove an extra space character? 😄 

I was going to do this after changing the headers so this wouldn't be a problem, but if you've already done that in the current version, that's cool, too.
