### ISSUE TITLE
How to  load data

### ISSUE THREAD

**Issue by Amber1990Zhang** [krlawrence/graph#168]
I'm using the gremlin console [docker](https://hub.docker.com/r/tinkerpop/gremlin-console/) on Mac.  I don't follow the instructions in **_2.6. Loading the air-routes graph using the Gremlin console_**. I don't know where to download the file `load-air-routes-graph.groovy` and `air-routes.graphml`.
![image](https://user-images.githubusercontent.com/42762957/75952751-93029680-5eea-11ea-9fb2-942d277f206c.png)

**Comment by krlawrence** [comment]
As documented in the manuscript all sample code and data is in the repo. Please try looking here:
https://github.com/krlawrence/graph/tree/master/sample-data

**Comment by jcjp** [comment]
I am having issue as well on loading the sample data `air-routes-latest.graphml` tried using `:load` or the function `graph.io(graphml()).readGraph('air-routes.graphml')` here is my exact terminal:

```
gremlin> :load air-routes.graphml
File not found: "air-routes.graphml"
gremlin> :load ./air-routes.graphml
File not found: "./air-routes.graphml"
gremlin> graph.io(graphml()).readGraph('air-routes.graphml')
air-routes.graphml (No such file or directory)
Type ':help' or ':h' for help.
```

I also tried using the exact path or using `~` but no luck as well. I used curl to download the file and also tried cloning your repo and use only the sample data `air-routes.graphml` but still same error.

**Comment by krlawrence** [comment]
I was about to suggest trying the absolute path. Glad that you got it working.

**Comment by krlawrence** [comment]
Thanks for sharing. Looks useful!
