### ISSUE TITLE
No such property: mean for class: groovysh_evaluate

### ISSUE THREAD

**Issue by PavelVBushmakin** [krlawrence/graph#174]
```
g.withSideEffect("m",mean).withSideEffect("c",count).V().hasLabel('airport').values('runways').math('(_ - m)^2').sum().math('_ / c').math('sqrt(_)')

No such property: mean for class: groovysh_evaluate
Type ':help' or ':h' for help.
Display stack trace? [yN]
```
3.29.6. Calculating a standard deviation

**Comment by krlawrence** [comment]
It is calculated in the example above
```
mean=g.V().hasLabel('airport').values('runways').mean().next()

1.4309425014819206
```

**Comment by krlawrence** [comment]
I should probably add an example that does the whole thing in one query.

**Comment by krlawrence** [comment]
Closing as this is fixed and work has now started on the second edition. There will likely be one final release of the v283 first edition line before the V2 branch becomes the second edition. That release will include these fixes.
