### ISSUE TITLE
Fix 7 Typos on reading material - (283-preview of the book)

### ISSUE THREAD

**Issue by sposhraj** [krlawrence/graph#180]
Sir,

It was great to get started with your book to learn about graph databases.
Below are the 7 typos which I noticed while reading your book.

### 4.7.4. Attaching multiple values (lists or sets) to a single property
If we wanted to store the IATA **amd** ICAO codes for the Austin airport in a list associated with a single property rather than
as separate properties we could have created them when we created the Austin vertex follows. You can also
add properties to an existing vertex that have lists of values. We will look at how to do that later in this section.
Suggestion: Fix Typo **amd** -> and

### 4.11.1. Basic sack operations
Now, each time the number of runways was added to the sack using a sum operator, the operation that was performed
was 1 + runways. As you can see from the results, in each case, the value returned is one higher than those from the
previous query. This is a very **dimple** example but hopefully you can start to see how useful sacks can be.
Suggestion: Fix Typo **dimple** -> simple

### 5.11. Finding unwanted parallel edges
The second gremlin query in this section has typo
g.V().has('code','LHR').out().groupCount().by('code').order(local).by(values,decr)**]**
Suggestion: Fix Typo - Discard **]** from the end of the query

### 5.2.1. Does any route exist between two **arirports**?
Suggestion: Fix Typo **arirports** -> airports (in the title itself)

### 6.6.3. Fuzzy search predicates
The first gremlin query in this section has typo
.V().has('desc',textContainsFuzzy("pall")).values('desc')
Suggestion: Fix Typo - Add **g** (missing) at the start of the query

### 7.8.9. Selected vertex information
The first gremlin query in this section has typo
g.V().hasLabel('airport').sample(3).
      union(id(),values('code','city'))**"**
Suggestion: Fix Typo - Discard **"** from the end of the query

### Table 8. Scope and ordering
The **fifth** row **first** column has the typo it should be "**asc**" rather than "**incr**"
Current :    incr        Order.asc           order().by(Order.asc)
Expected:    asc         Order.asc           order().by(Order.asc)

**Comment by krlawrence** [comment]
Thanks for taking the time to report these. I will verify against the latest draft and get them corrected as appropriate.

**Comment by sposhraj** [comment]
@krlawrence and @legobridge - looks like from above suggestions (second one [4.11.1. Basic sack operations]) seems to have been observed and rectified before https://github.com/krlawrence/graph/pull/160 , however that is **not** being correctly reflected here : https://kelvinlawrence.net/book/Gremlin-Graph-Guide.html

**Comment by sposhraj** [comment]
@krlawrence - closing this
