### ISSUE TITLE
Update documentation on deprecated addOutE method

### ISSUE THREAD

**Issue by cedtwo** [krlawrence/graph#199]
Section 4.5.1 of the book notes that both the `addOutE` and `addE` methods can be used to define the direction of an edge. However, the example for `addOutE`,
```
g.V().has('code','XYZ').as('a').V().has('code','DFW').addOutE('route','a')
```
raises the error:
```
No signature of method: org.apache.tinkerpop.gremlin.process.traversal.dsl.graph.DefaultGraphTraversal.addOutE() is applicable for argument types: (String, String) values: [route, a]
```
According to the deprecation list [here](http://tinkerpop.apache.org/javadocs/3.2.0-SNAPSHOT/full/deprecated-list.html), the method has been replaced by the `addE` method, and documentation makes no reference to `addOutE`.

**Comment by krlawrence** [comment]
I'll look into this and make the necessary changes.

**Comment by krlawrence** [comment]
Removed the example, changed and improved the narrative and added a tip that the `addOutE` step was removed from the language.

**Comment by krlawrence** [comment]
Closing as this is fixed and work has now started on the second edition. There will likely be one final release of the v283 first edition line before the V2 branch becomes the second edition. That release will include these fixes.
