### ISSUE TITLE
mobi format

### ISSUE THREAD

**Issue by trojek** [krlawrence/graph#2]
I convert for my own needs your book to Mobi format. Would you like pull request?

**Comment by krlawrence** [comment]
Hi @trojek is there an easy way to make a Mobi that you would recommend? I would be happy to make one as part of my standard workflow if there is an easy way. As the book remains a work in progress it would be good to have the mobi keep up with the HTML and PDF versions.

**Comment by trojek** [comment]
Hi @krlawrence, there exist an easy way to make a Mobi. I use Ubuntu based system and do it as follows (in graph/book folder):
```
asciidoctor -d book -b docbook5 Gremlin-Graph-Guide.adoc -o Gremlin-Graph-Guide.docbook
pandoc -f docbook -t epub Gremlin-Graph-Guide.docbook -o Gremlin-Graph-Guide.epub
ebook-convert Gremlin-Graph-Guide.epub Gremlin-Graph-Guide.mobi
```
I didn't test the third command. I used Caibre (GUI application) to convert it. I found information that `ebook-convert` the same program which Caibre use in order to convert epub to Mobi.

As you can see as a result you will get books in two "e-paper" formats: Mobi an epub. 

If you use Linux I can prepare script which will convert (and remove *.docbook) your book automatically.

**Comment by krlawrence** [comment]
Thanks @trojek I will be working on the book over the coming weekend and will look at this. I actually also use Ubuntu to run Asciidoctor so this is convenient. I will try and add producing mobi to my standard workflow,

**Comment by krlawrence** [comment]
I have added DOCBOOK, MOBI and EPUB to my standard workflow. Added those formats to the /book folder.
