### ISSUE TITLE
Typo in the last paragraph of section 4.19.1

### ISSUE THREAD

**Issue by shiyeling** [krlawrence/graph#204]
In the latest online version,

The first sentence of last paragraph in section 4.19.1 reads: 
"Notice that for the clock and **clockWithReslts** methods to work correctly you need to end the query with a termination step such as next or toList. "

I think it should be "clockWithResult" ??

**Comment by krlawrence** [comment]
Thank you for taking the time to let me know about this. Very much appreciated.

**Comment by krlawrence** [comment]
Closing as this is fixed and work has now started on the second edition. There will likely be one final release of the v283 first edition line before the V2 branch becomes the second edition. That release will include these fixes.
