### ISSUE TITLE
fix typogarphical nits

### ISSUE THREAD

**Issue by bobsut** [krlawrence/graph#208]
Several occurrences of **`it's`** (contraction) should be **`its`** (possessive).
Varying whitespace makes for lumpy reading.

**Comment by krlawrence** [comment]
Thanks for taking the time to submit changes. I made a comment on #209 regarding extra spaces.

**Comment by krlawrence** [comment]
PR #209 was merged to resolve this issue.

**Comment by bobsut** [comment]
I just noticed this lingering as an open issue.
Sorry about that! I didn't mean to skew your stats.
I thought it would be auto-closed when it got Fixed or Complete or some other state transition.
