### ISSUE TITLE
Do you have plans for translating to other languages, like Chinese？

### ISSUE THREAD

**Issue by shiyeling** [krlawrence/graph#211]
Graph DB is getting hot recently in China and I think this tutorial could be very helpful to newbies of the Graph DB world.
Is there any plan to translate it to Chinese?

**Comment by krlawrence** [comment]
I was approached a while back by someone asking if they would mind if they translated everything into Chinese. I had asked that if they did they keep me informed and consider donating the translated version back. I have heard nothing since. Unfortunately I do not speak Chinese so any work to make a translation would have to be done by Chinese speakers willing to invest the time and ideally to donate back so others could benefit from the work.

**Comment by shiyeling** [comment]
Interesting. That's not me for sure. I'm having the same idea, to be honest. 
I did a quick search in baidu.com, taobao.com and jd.com (they are google and amazon in China ) and could not find similar thing related to keyword 'practical gremlin', so I guess that guy didn't really proceed as he planned.

I think you've organized the tutorial in a quite systematical way and the content is really helpful for anyone who want's to play with graphs. Although the audience group would be  small, but I think its worth doing.

What kind of tools do you use to maintain this repo? Point me to a guide and I will try to figure out how to get started.

Once I get it started,  hopefully I can spare some time every week to make some progress.

**Comment by tkaneda** [comment]
Hi all. 
Nice to meet you.
Now I am translating the book into Japanese. 
Thanks for good document.

Sorry for just only FYI.

**Comment by krlawrence** [comment]
Thanks for letting me know @tkaneda and best of luck with your work - please share a link when it is ready.

**Comment by tkaneda** [comment]
I want to send pull request for japanese-translated files.
What can I do for it?
thanks.

**Comment by tkaneda** [comment]
@krlawrence  Have you read this?

**Comment by tkaneda** [comment]
OK.
So,　I will adjust the directory structures and bring it up.

**Comment by tkaneda** [comment]
@krlawrence 
done.
I sent pull request.
thanks.

**Comment by krlawrence** [comment]
Thanks for all the work you put into this. We are going to start work on a Second Edition. That work will for now take place in the V2 branch.
