### ISSUE TITLE
Update coalesce example for best practice

### ISSUE THREAD

**Issue by bechbd** [krlawrence/graph#221]
For the example shown here: https://kelvinlawrence.net/book/Gremlin-Graph-Guide.html#upsert

This would be simpler if written as below since the same property value is being set.
```
g.V(3).fold().
       coalesce(unfold(),
       addV('airport')).property('runways',3)
```
It would also be good to show an example where you set different properties on create versus update portions of this pattern.

**Comment by spmallette** [comment]
We could probably close this one in favor of `mergeV()` - i suppose we might keep some `fold()/coalesce()/unfold()` examples for the sake of antiquity though as part of doing that.
