### ISSUE TITLE
Cannot find link to air-routes.graphml on the html version of the book

### ISSUE THREAD

**Issue by viebel** [krlawrence/graph#23]

**Comment by krlawrence** [comment]
Hi @viebel could you add a description please that describes in more detail what I should fix? Are you suggesting I add a link to the Github repository?

**Comment by viebel** [comment]
Hi @krlawrence 

I suggest that you add a link to the `air-route.graphml` file inside the html version of the book.

Otherwise, it is impossible for the readers to run the code snippets that appear in the book.

**Comment by krlawrence** [comment]
Thanks for the feedback @viebel I will add that for the next release (v275)

**Comment by krlawrence** [comment]
I just added a section near the start that has links to the various parts of the Git repo
Here is the commit. https://github.com/krlawrence/graph/commit/370c1a4e8e96b8f0c561f146b0a491fcbf42aea3#diff-0296601442c3c7cd82a899ae19e58c21

Please close this issue once you have a chance to review. @viebel

**Comment by viebel** [comment]
Great.
Thanks
