### ISSUE TITLE
kelvinlawrence.net is not available

### ISSUE THREAD

**Issue by zhulik** [krlawrence/graph#236]
Hello, 

I'm not sure if it's a right place to ask, but it seems like kelvinlawrence.net is not delegated anymore https://www.nslookup.io/dns-records/kelvinlawrence.net and it's not possible to read the book online or download it.

**Comment by krlawrence** [comment]
Sorry about that - should be fixed now - the auto renewal of the domain name had an issue.

**Comment by zhulik** [comment]
Amazing! Thanks a lot
