### ISSUE TITLE
Add comma at 3.1 - Introducing Gremlin

### ISSUE THREAD

**Issue by asafgamliel** [krlawrence/graph#247]
Using Gremlin we can traverse a graph looking for values, patterns and relationships `,` we can add or delete vertices and edges, we can create sub-graphs and lots more.

**Comment by krlawrence** [comment]
Thanks very much for taking the time to report this. Work is just getting underway on a second edition but we can also fix this one in the first edition line.

**Comment by krlawrence** [comment]
After looking at how quickly the second edition work is progressing, I just went ahead and fixed it there. We'll have a first preview version fairly soon.
