### ISSUE TITLE
Setting properties stored in an object/dict

### ISSUE THREAD

**Issue by vapps-team** [krlawrence/graph#248]
Is it possible to set an arbitrary number of properties stored in a JS object, python dict, etc.?

E.g., 

var properties = { a: 1, b: 2, c: [3, 4]};
g.addV('type').properties(properties);

Would add the following properties:

- a: 1
- b: 2
- c: [3, 4]

**Comment by krlawrence** [comment]
Thanks for the question. The ability to pass a map of key/value pairs to the `property` step was added to Gremlin as part of the TinkerPop 3.6.0 release.

**Comment by krlawrence** [comment]
I'm going to close the issue but please feel free to re-open if you have additional questions.
