### ISSUE TITLE
GraphSON typed vs untyped

### ISSUE THREAD

**Issue by spmallette** [krlawrence/graph#256]
There is mention of how GraphSON has typed and untyped versions in "Beyond Basic Queries" but we now have untyped GraphSON for versions 2 and 3 as of 3.6.5 which begs some discussion: 

https://tinkerpop.apache.org/docs/current/upgrade/#_untyped_graphson

**Comment by krlawrence** [comment]
We may want to merge this issue, and this other really old one https://github.com/krlawrence/graph/issues/31
