### ISSUE TITLE
Refresh the Introduction for V2

### ISSUE THREAD

**Issue by spmallette** [krlawrence/graph#258]
The V2 section uses first person singular a fair bit. I left that alone when converting the rest of the document to first person plural because the introduction is a bit of a personal note from @krlawrence so the "I" for many paragraphs makes sense. As such, it probably needs his attention to make that nice. for the second edition.

**Comment by krlawrence** [comment]
I have done a pretty major update to the first two chapters spread across several issues (including #263), multiple commits, and also this PR #266 . Let me know what you think and if more is needed. I imagine doing a complete re-read and re-work as needed once more of the core material has been updated.

**Comment by krlawrence** [comment]
Closing for now - as we approach a release of the second edition we should revisit this section
