### ISSUE TITLE
gremlin-server-air-routes-yaml fails on gremlin server 3.6.2 & 3.7: Unable to find property 'scriptEvaluationTimeout'

### ISSUE THREAD

**Issue by noahehall** [krlawrence/graph#267]
- fixed by commenting this line `scriptEvaluationTimeout: 30000`

> sample log

```sh

$ ./gconsole.sh


[+] Running 1/0
 ✔ Container gserver  Created                                                                        0.0s 
Attaching to gserver
gserver  | [INFO] o.a.t.g.s.GremlinServer - 3.7.0
gserver  |          \,,,/
gserver  |          (o o)
gserver  | -----oOOo-(3)-oOOo-----
gserver  | 
gserver  | Oct 07, 2023 12:43:33 PM org.yaml.snakeyaml.internal.Logger warn
gserver  | WARNING: Failed to find field for org.apache.tinkerpop.gremlin.server.Settings.plugins
gserver  | [ERROR] o.a.t.g.s.GremlinServer - Configuration file at conf/gremlin-server.yaml could not be found or parsed properly. [Cannot create property=scriptEvaluationTimeout for JavaBean=org.apache.tinkerpop.gremlin.server.Settings@6221a451
gserver  |  in 'reader', line 3, column 1:
gserver  |     host: 172.20.0.2
gserver  |     ^
gserver  | Unable to find property 'scriptEvaluationTimeout' on class: org.apache.tinkerpop.gremlin.server.Settings
gserver  |  in 'reader', line 5, column 26:
gserver  |     scriptEvaluationTimeout: 30000
gserver  |                              ^
gserver  | ]
gserver exited with code 0

```

**Comment by noahehall** [comment]
I was able to get gremlin-server + gremlin-console running using your data files in docker compose.

I ended up having to deviate a bit from the instructions in the book

- https://github.com/nirv-ai/dbs/tree/main/graph/tinkerpop/run.sh

**Comment by krlawrence** [comment]
Thanks for the report. `scriptEvaluationTimeout` was deprecated in favor of `evaluationTimeout` but for a long time both worked. It looks like the prior form was fully removed in the 3.5.0 release. https://github.com/apache/tinkerpop/blob/master/CHANGELOG.asciidoc#tinkerpop-350-release-date-may-3-2021

Work has started on a second edition. We'll fix up the YAML as part of that.

**Comment by noahehall** [comment]
> Work has started on a second edition. We'll fix up the YAML as part of that.

looking forward to it! your book is a lifesaver for ramping up on gremlin
