### ISSUE TITLE
Change book title to Practical Gremlin

### ISSUE THREAD

**Issue by krlawrence** [krlawrence/graph#29]
I have had a few people point out that the current title of the book (Graph Databases, Gremlin and TinkerPop - a Tutorial)  is a bit of a mouthful to quote when referencing this work. I agree! Moving forward I am going to rename the book "Practical Gremlin" with a subtitle of something like "An Apache TinkerPop Tutorial" This way we can all just refer to Practical Gremlin - much simpler!

**Comment by pluradj** [comment]
You'll probably also want to update the project description on the GitHub repo and the URL on your personal website.

**Comment by krlawrence** [comment]
Yes, thanks @pluradj I'll work on that over the weekend and I'll do a release to get an updated PDF etc out there. BTW The PDF looks nice now I switched to asciidoctor-pdf

**Comment by krlawrence** [comment]
Fixed in release #v276
