### ISSUE TITLE
TYPO ? : 6.1.3. Compiling our code 

### ISSUE THREAD

**Issue by victorgrappe** [krlawrence/graph#30]
Hi, 

They may be a typo in the CP variable in section "6.1.3. Compiling our code" :

-------- ORIGINAL (full) -----------------------------------
GREMLIN=...
LIBPATH=$GREMLIN/lib/*
EXTPATH=$GREMLIN/ext/*
ADDL=$GREMLIN/ext/tinkergraph-gremlin/lib/*
export CP=$CLASSPATH:$LIBPATH/*:$EXTPATH/*:$ADDL
javac -cp $CP TinkerGraphTest.java

-------- CORRECTION SUGGESTION (one line) ---
export CP=$CLASSPATH:$LIBPATH:$EXTPATH:$ADDL
(suppression of the "/*" after "$LIBPATH" and "$EXTPATH")

-------- JUSTIFICATION ---------------------------------
The "/*" is already at the end of the "LIBPATH" and "EXTPATH" 
The result when i do: "echo $CD" is variables names ending with "/*/*" (concatenation)

I've successfully compiled the "first TinkerPop Java program" with the corrected version while I had errors with the original one.

For information, I used Ubuntu 16.04 LTS

Best regards,

Victor

**Comment by krlawrence** [comment]
Thanks Victor - I'll make sure it is corrected

**Comment by krlawrence** [comment]
V277 released today.
