### ISSUE TITLE
Code typo - Section 2.3 Introducing TinkerGraph

### ISSUE THREAD

**Issue by neilkidd** [krlawrence/graph#32]
Hi,
Many thanks for your work 🥇 

In the code listing in section 2.3, at the prompt:
`> GraphFeatures ...`
should be:
`> graph.features() ...`

If this helps and it's the type of feedback you would like - let me know and I'll try and contribute.

**Comment by krlawrence** [comment]
Hi Neil - I appreciate all feedback. That is not actually meant to be a prompt. That is the output that comes back from `graph.features()` - I should clarify that in the text better. /CC @neilkidd

**Comment by krlawrence** [comment]
V277 released today.
