### ISSUE TITLE
lowercased Gremlin queries

### ISSUE THREAD

**Issue by pluradj** [krlawrence/graph#33]
In section 4.7.4. "Attaching multiple values (lists or sets) to a single property" http://kelvinlawrence.net/book/Gremlin-Graph-Guide.html#listprop it looks like the Gremlin queries all got lowercased. For example:

```
g.v().has('code','aus').valuemap()
```

should be:

```
g.V().has('code','AUS').valueMap()
```

**Comment by krlawrence** [comment]
Thanks Jason - seems my editor when on the rampage in that section and removed ALL upper case characters!

**Comment by krlawrence** [comment]
V277 released today.
