### ISSUE TITLE
Small typo in 3.3, v278-preview

### ISSUE THREAD

**Issue by gabelucci** [krlawrence/graph#38]
In v278-preview Section 3.3, 2nd paragraph, last sentence:

> These steps tell Gremlin which places to move to **next next** as it traverses a graph for you.

"next" is accidentally written twice. Should be:
> These steps tell Gremlin which places to move to **next** as it traverses a graph for you.

**Comment by krlawrence** [comment]
Will be fixed in next release. Fix already committed. Thanks for finding this!

**Comment by krlawrence** [comment]
Fixed in the v278 (TP 3.3.1) release.
