### ISSUE TITLE
REPL - Read Execute Print Loop?

### ISSUE THREAD

**Issue by Infir3** [krlawrence/graph#41]
Only a minor issue and I might be wrong, but I know this term as Read **Eval** Print Loop.

**Comment by krlawrence** [comment]
Thanks , good catch @Infir3 Stefan and thanks for taking the time to open an issue. I will fix it today and upload a new snapshot.

**Comment by krlawrence** [comment]
Fixed in the v278 (TP 3.3.1) release.
