### ISSUE TITLE
Add coverage of Gremlin console color coding settings

### ISSUE THREAD

**Issue by krlawrence** [krlawrence/graph#49]
Should add some coverage of the settings that allow the output from the Gremlin console to be color coded to the Gremlin console introduction section. The official docs have coverage of these settings at https://tinkerpop.apache.org/docs/current/reference/#gremlin-console

**Comment by chencjiajy** [comment]
I have used in Gremlin console with command `:set gremlin.color bg_black,green,bold`  which is introduced in [links](https://github.com/apache/tinkerpop/blob/master/docs/src/reference/gremlin-applications.asciidoc#console-preferences), but my Gremlin console still remains black and white.
Could you please tell me how you achieve the color coding in your book.

**Comment by krlawrence** [comment]
The color coding in the book was done using a tool outside the console called Pygments.

This worked fine for me:  `:set gremlin.color bg_black,green,bold` in a Mac Terminal window.

Is it possible your terminal does not have colors enabled?

**Comment by chencjiajy** [comment]
Thanks for your reply, I also tried it in a Mac Terminal window. I have enabled colors in .bash_profile. Maybe I'll find the reason later
