### ISSUE TITLE
Explanation in details the sql2gremlin queries

### ISSUE THREAD

**Issue by awill2** [krlawrence/graph#6]
The http://sql2gremlin.com/ has some queries I'm trying to understand what they do and why this is done that way. What this commands produce as result.... Wold be nice to have some clarification on that.

**Comment by krlawrence** [comment]
Could you maybe give an example of some specific Gremlin that you are trying to understand so I can think about where I should add more coverage? Thanks.

**Comment by emehrkay** [comment]
While @awill2 didn't give concrete examples in his question, I totally understand the line of thought. I've see a lot of gremlin functions used that aren't described in the doc or if they are, they aren't described too well. 

The first time I saw the `project` step was in the Datastax videos  https://academy.datastax.com/resources/gremlin-recipes?unit=recommendation-engine-gremlin-gremlin-recipes. Duyhai Doan does a great job of explaining the various steps and the types of objects that they produce and how to use those types. I also feel like he does it in a way that allows one to bridge the sql gap. 

I'm not too sure if your document should go into that much detail, but having that kind of information would be useful for people to learn with.

**Comment by krlawrence** [comment]
Could you give me an example of where I do not go into enough detail or where I have a gap? I have a lot of these type of things already covered so would appreciate a specific example of a section in my doc where I should add something. Many thanks.

**Comment by emehrkay** [comment]
I don't think there is anything more you should cover in your document. I do think that a huge part of understanding and utilizing gremlin, on a deeper level, relies on understanding some java and how to handle its various datatypes (map vs flatmap etc). 

To me, Gremlin seems to be a language where one simply transforms the output from the previous step into something else. And you do a great job explaining that. The roadblock for me, and I'm certain a lot of other learners, is knowing which steps to take in which order to get the desired result and I believe that is what @awill2 was speaking to. And like I said, it may be out of scope for what you are doing with this document.

When I said `I've see a lot of gremlin functions used that aren't described in the doc or if they are, they aren't described too well.` I was talking about around the web, not in your document sorry for that confusion. I think the work that you've done is great and I will be using it to help introduce graph DBs/gremlin to a host of newbies (I'll share the results soon). I'm sure I will have feedback for the document based on that experience and I am happy to send some pull requests your way.

Thanks for the hard work.

**Comment by krlawrence** [comment]
I will see, when I focus more on the coding sections (section 6 in particular) if I can cover more of what you describe. Thanks for the clarifications @emehrkay

**Comment by krlawrence** [comment]
I believe I have (hopefully anyway) now improved the coverage in these areas  I am going to tag this as fixed but please let me know if you still see any gaps.
