### ISSUE TITLE
Can I get all vertexes and edges from the following query using repeat step ?  g.V().repeat(both()).times(2).path()

### ISSUE THREAD

**Issue by anglepei** [krlawrence/graph#72]
Can I get all vertexes and edges from the following query using repeat step ? 
g.V().repeat(both()).times(2).path()

**Comment by krlawrence** [comment]
Hi @anglepei ,

If you want everything in the graph you can just do this:

`g.V().outE().inV().path()`

Note that this will miss any vertices that have no edges. 

See also this post on the Gremlin users list:

https://groups.google.com/forum/#!topic/gremlin-users/_4wqID5d4Bw

**Comment by krlawrence** [comment]
Closing as this is really just a question. I hope my answer was helpful.

**Comment by anglepei** [comment]
@krlawrence 
Thank you very much. can not do it with repeat? I could repeat many times.
