### ISSUE TITLE
Gremlin query not working 

### ISSUE THREAD

**Issue by nitin9nair** [krlawrence/graph#8]
**g.V().hasLabel('airport').groupCount().by('country').order(local).by(valueDecr)**

The above query is not working as it is not displaying the number of airports in decreasing order but only displaying its list.

Please, check the above issue and reply.

One more issue how to find the country having the highest number of airports ?

Thanks for the wonderful book you have written.

**Comment by krlawrence** [comment]
Here is what I get when I run the query - what could I do better?

g.V().hasLabel('airport').groupCount().by('country').order(local).by(valueDecr)
==>[US:579,CN:209,CA:203,AU:124,RU:120,BR:115,IN:73,ID:67,JP:63,MX:59,UK:58,FR:58,CO:50,NO:49,TR:48,IR:44,ES:42,SE:39,GR:39,PH:38,AR:36,IT:36,MY:34,DE:33,TH:32,PF:30,DZ:29,SA:26,VU:26,PG:26,NZ:25,VE:24,VN:21,PK:21,FI:20,ZA:20,KZ:20,PE:20,BS:18,NG:18,SB:17,CL:17,BO:15,UA:15,EC:15,KR:15,PT:14,AO:14,RO:14,ET:14,GL:14,KE:14,MA:14,MM:14,BZ:13,CR:13,MG:13,PL:13,CU:12,CD:11,UZ:11,AE:10,EG:10,FJ:10,LY:10,MN:10,MZ:10,NP:10,TW:9,YE:9,TN:8,TZ:8,DK:8,HR:8,ZM:8,LA:8,MV:8,BD:7,CV:7,DO:7,IE:7,PR:6,AT:6,CK:6,HN:6,IQ:6,LK:6,AZ:5,BE:5,SD:5,SO:5,CH:5,CM:5,CZ:5,GH:5,IL:5,IS:5,NL:5,PA:5,AF:4,BA:4,BG:4,BW:4,TC:4,TJ:4,UG:4,FM:4,NA:4,OM:4,BQ:3,SN:3,CG:3,CY:3,EE:3,GE:3,ZW:3,KH:3,KY:3,LT:3,MR:3,PY:2,AM:2,RE:2,RS:2,BF:2,RW:2,SC:2,SH:2,BY:2,SK:2,SY:2,TT:2,EH:2,UY:2,VG:2,VI:2,FK:2,WF:2,GA:2,GG:2,GQ:2,GT:2,GY:2,HT:2,HU:2,JM:2,JO:2,KG:2,KI:2,KN:2,LC:2,LR:2,ME:2,MH:2,MP:2,MU:2,MW:2,PW:1,QA:1,AG:1,AI:1,AL:1,AS:1,AW:1,BB:1,BH:1,BI:1,BJ:1,BL:1,BM:1,BN:1,BT:1,SG:1,SI:1,SL:1,SR:1,SS:1,CC:1,ST:1,SV:1,CF:1,SX:1,CI:1,SZ:1,TD:1,TG:1,CW:1,CX:1,TL:1,TM:1,TO:1,TV:1,DJ:1,DM:1,ER:1,VC:1,FO:1,WS:1,GD:1,GF:1,GI:1,GM:1,GN:1,GP:1,GU:1,GW:1,HK:1,YT:1,IM:1,JE:1,KM:1,KP:1,KS:1,KW:1,LB:1,LS:1,LU:1,LV:1,MD:1,MF:1,MK:1,ML:1,MO:1,MQ:1,MS:1,MT:1,NC:1,NE:1,NF:1,NI:1,NR:1,PM:1]

@nitin9nair

**Comment by nitin9nair** [comment]
Hi, thanks for the quick response.

I am using **Gremlin Console version 3.3.0**.

Here is what I get now when I run the query.

```
gremlin> g.V().hasLabel('airport').groupCount().by('country').order(local).by(valueDecr)
No such property: valueDecr for class: groovysh_evaluate
Type ':help' or ':h' for help.
Display stack trace? [yN]
```
Below is what I get when I remove the **'local'** and use **'decr'** instead of **'valueDecr'**

```
gremlin> g.V().hasLabel('airport').groupCount().by('country').order().by(decr)
==>[PR:6,PT:14,PW:1,PY:2,QA:1,AE:10,AF:4,AG:1,AI:1,AL:1,AM:2,AO:14,AR:36,AS:1,RE:2,AT:6,AU:124,AW:1,AZ:5,RO:14,BA:4,BB:1,RS:2,BD:7,RU:120,BE:5,BF:2,RW:2,BG:4,BH:1,BI:1,BJ:1,BL:1,BM:1,BN:1,BO:15,SA:26,BQ:3,SB:17,BR:115,SC:2,BS:18,SD:5,SE:39,BT:1,SG:1,SH:2,BW:4,SI:1,BY:2,BZ:13,SK:2,SL:1,SN:3,SO:5,CA:203,SR:1,CC:1,SS:1,CD:11,ST:1,SV:1,CF:1,CG:3,SX:1,CH:5,SY:2,CI:1,SZ:1,CK:6,CL:17,CM:5,CN:209,CO:50,CR:13,TC:4,TD:1,CU:12,CV:7,TG:1,CW:1,TH:32,CX:1,CY:3,TJ:4,CZ:5,TL:1,TM:1,TN:8,TO:1,TR:48,TT:2,DE:33,TV:1,TW:9,TZ:8,DJ:1,DK:8,DM:1,DO:7,UA:15,UG:4,UK:58,DZ:29,US:579,EC:15,EE:3,EG:10,EH:2,UY:2,UZ:11,VC:1,ER:1,ES:42,VE:24,ET:14,VG:2,VI:2,VN:21,VU:26,FI:20,FJ:10,FK:2,FM:4,FO:1,FR:58,WF:2,GA:2,WS:1,GD:1,GE:3,GF:1,GG:2,GH:5,GI:1,GL:14,GM:1,GN:1,GP:1,GQ:2,GR:39,GT:2,GU:1,GW:1,GY:2,HK:1,HN:6,HR:8,YE:9,HT:2,HU:2,ID:67,YT:1,IE:7,IL:5,IM:1,IN:73,ZA:20,IQ:6,IR:44,IS:5,IT:36,ZM:8,JE:1,ZW:3,JM:2,JO:2,JP:63,KE:14,KG:2,KH:3,KI:2,KM:1,KN:2,KP:1,KR:15,KS:1,KW:1,KY:3,KZ:20,LA:8,LB:1,LC:2,LK:6,LR:2,LS:1,LT:3,LU:1,LV:1,LY:10,MA:14,MD:1,ME:2,MF:1,MG:13,MH:2,MK:1,ML:1,MM:14,MN:10,MO:1,MP:2,MQ:1,MR:3,MS:1,MT:1,MU:2,MV:8,MW:2,MX:59,MY:34,MZ:10,NA:4,NC:1,NE:1,NF:1,NG:18,NI:1,NL:5,NO:49,NP:10,NR:1,NZ:25,OM:4,PA:5,PE:20,PF:30,PG:26,PH:38,PK:21,PL:13,PM:1]
gremlin>
```

Please help me to solve this issue.

@krlawrence

**Comment by krlawrence** [comment]
I'm glad you found this @nitin9nair looks like in 3.3 it needs to change to this syntax. I will update the book.

g.V().hasLabel('airport').groupCount().by('country').order(local).by(values,decr)

**Comment by krlawrence** [comment]
I have fixed all occurrences of this issue in the revision 270 that was just posted. Thanks again for finding these!

**Comment by nitin9nair** [comment]
Thanks @krlawrence for the changes.

**Comment by nitin9nair** [comment]
How to get values in sync according to the query ?

Query :
```
 g.V().has('code',within('BOM','SFO','DEL','AUS','AGR')).values('city')
==>Austin
==>San Francisco
==>New Delhi
==>Mumbai
==>Agra
```

The above query gave the correct result but not in order of asked query. The result should be in accordance to the query being given as shown below that is to give cities in order to their airport code.

```
 g.V().has('code',within('BOM','SFO','DEL','AUS','AGR')).values('city')
==>Mumbai
==>San Francisco
==>New Delhi
==>Austin
==>Agra
```
@krlawrence

**Comment by krlawrence** [comment]
Hi @nitin9nair Please can I ask that you open new issues for new topics.  I do not believe that Tinkerpop makes any guarantee as to order. Remember multiple traversers will be fired off and results will be returned in the order they are found. You should not write code that relies on the order. If you need to sort the results you can add an order() step to guarantee the results will be sorted.
