### ISSUE TITLE
Section 3.3.5. Using multiple as steps with the same label

### ISSUE THREAD

**Issue by XingkaiJ** [krlawrence/graph#82]
Section 3.3.5. Using multiple as steps with the same label
when I run this query on janusgraph 0.2.0
g.V(1).as('a').V(2).as('a').select('a')

return:
[v[1],v[2]]

**Comment by krlawrence** [comment]
JanusGraph 0.2.0 supports an older version of TinkerPop so the behavior of some queries may be different. It looks like JanusGraph acts as if `select(all,'a')` was used. @pluradj Do you . have any additional insight you can share for @XingkaiJ ? When I run the query using TinkerGraph and TinkerPop 3.3.1 or later the results are as follows

```
gremlin> g.V(1).as('a').V(2).as('a').select('a')
==>v[2]
gremlin> g.V(1).as('a').V(2).as('a').select(all,'a')
==>[v[1],v[2]]
```

**Comment by krlawrence** [comment]
I am going to close this issue as it has been several days since I provided an answer. Please feel free to re-open if you think there is something I need to change. Hopefully JanusGraph will be updated to the latest TinkerPop level very soon.
