### ISSUE TITLE
Section 6.3.6 second code snippet uses 'myList' instead of 'mylist'

### ISSUE THREAD

**Issue by alexemmons** [krlawrence/graph#84]
I went through the example using the 'chained' code snippet, then had trouble with the following examples because I had used 'myList' instead of 'mylist'.

mgmt.makePropertyKey('**myList**').dataType(String.class).cardinality(LIST).make()

**Comment by krlawrence** [comment]
Thanks for the feedback. I'll make the fixes.

**Comment by krlawrence** [comment]
Included in v279-3.3.3 release. May 29, 2018
