### ISSUE TITLE
Unable to load GraphML

### ISSUE THREAD

**Issue by swarncar** [krlawrence/graph#9]
Getting the following error on loading air-routes.graphml on Tinkerpop 3:
com.ctc.wstx.exc.WstxUnexpectedCharException: Unexpected character '>' (code 62) expected '='
 at [row,col {unknown-source}]: [42,92]

**Comment by krlawrence** [comment]
Hi @swarncar Could you please paste here the exact steps you are using to load the file. I know the file is working for others and lots of people have been able to load it but I would like to figure out why it is not working for you. Could you do an MD5 sum on your version and I can do one on the one here and make sure that they match as a further double check.

**Comment by krlawrence** [comment]
FYI I downloaded the air-routes.graphml file and loaded it myself into the Gremlin console and it worked fine. The MD5SUM is 98183c1e16a619c5900d88f5d326e9ea

**Comment by krlawrence** [comment]
Hi @swarncar I have not been able to reproduce your issue. If you are able to verify that your MD5 value matches mine and are able to reproduce the error using the loading steps in the book please re-open the issue and add as much detail as you can. Many thanks.
