### ISSUE TITLE
Typo or bug - section 3.3.2

### ISSUE THREAD

**Issue by rengel-de** [krlawrence/graph#96]
In the first example the output data show:
gremlin> g.V().has('airport', 'code', 'LCY').outE().inV().path()
==>[v[88],e[13696][88-route->74],v[74]]
==>[v[88],e[13697][88-route->76],v[76]]
==>[v[88],e[13698][88-route->77],v[77]]      <==
==>[v[88],e[13699][88-route->84],v[84]]
==>[v[88],e[13700][88-route->90],v[90]]
...

In the book there is a different output:
v[88],e[13208][88-route->77],v[77]]

The same goes for the second example where the book shows the result

[LCY,468,GVA]

but the data show

[LCY,456,GVA]

... and again for the last example in this section.

**Comment by krlawrence** [comment]
Thanks. I'll do some checking and make sure everything is consistent.

**Comment by krlawrence** [comment]
Not sure what happened there. Thanks for the thorough review! Fixed.

**Comment by krlawrence** [comment]
Fixed in Release 280
