### ISSUE TITLE
Unclear expression - section 3.3.2

### ISSUE THREAD

**Issue by rengel-de** [krlawrence/graph#97]
From section 3.3.2:

... The by modulators are processed in a round robin fashion. So even though there are three values we want to have formatted, we only need to specify two by modulators **as both the first and third values are the same**...

Is this correct? As I understand it, the values (i.e. 'LCY' and 'MAD' in the first result) are different, but the **selected property** ('code') is the same. So we are having three output values but only two **types** of output values.

This might be a semantic issue. In common sense, the strings 'LCY' and 'MAD' are values proper while the expression "values('code')" is a command to return these values.

**Comment by krlawrence** [comment]
I'll look at possibly improving the wording. The word 'values' is probably confusing here. Thanks for the feedback.

**Comment by krlawrence** [comment]
Clarified the wording.

**Comment by krlawrence** [comment]
Fixed in Release 280
