### ISSUE TITLE
Definition of modulator - section 3.3.2

### ISSUE THREAD

**Issue by rengel-de** [krlawrence/graph#99]
From section 3.3.2

> While this is useful, we might want to return something more human readable such as the IATA
> codes for each airport and perhaps the distance property from the edge that tells us how far apart
> the airports are. We could add some _by_ modulators to our query to do this. 
>
While one can deduce  the meaning of the new term 'modulator' means from the context, it might be helpful to insert here a short definition.

**Comment by krlawrence** [comment]
Agreed. I will add an explanation and maybe a tip box also. This is great feedback thanks @rengel-de

**Comment by krlawrence** [comment]
Fixed in Release 280
